name: exploit

on: push

env:
  PNPM_VERSION: '9.9'
  NODE_VERSION: '20.11'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install huff
        uses: huff-language/huff-toolchain@v3
        with:
          version: nightly

      - name: Display tool versions
        run: |
          forge --version
          huffc --version

      - name: Build contracts
        run: pnpm run build
        id: build

      - name: Run exploits
        run: pnpm run exploits
        id: test
